Titanic Advanced: Large-Scale Ensemble of Honest Trees using TensorFlow

## Libraries

In [5]:
import tensorflow_decision_forests as tfdf
import pandas as pd
import tensorflow as tf

In [6]:
import numpy as np
import matplotlib.pyplot as plt

## Carga de los datos

### Cargar el entrenamineto

In [7]:
train_df = pd.read_csv("train.csv")

### Cargar el test

In [8]:
serving_df = pd.read_csv("test.csv")

### Verificacion de la carga

In [9]:
print("Entrenamiento:")
display(train_df.head(3))

print("\nTest (Serving):")
display(serving_df.head(3))

Entrenamiento:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

Test (Serving):

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q